### ISSUE TITLE
FDS: Ai Senshi Nicol [Bug]

### ISSUE THREAD

**Issue by ValiumBear** [libretro/Mesen#41]
On level 3 the game becomes buggy. It's the same bug as this: https://github.com/SourMesen/Mesen/issues/611
![Ai Senshi Nicol Visual Bug](https://github.com/libretro/Mesen/assets/56096164/3adadffd-c60b-4c7f-8692-8761308825b2)

Core: Libretro Mesen (0.9.9) core and **non bad dump** of FDS game "Ai Senshi Nicol" [CRC32: 3FBDBE79]
The same bug appears in standalone Mesen2 Dev Build (2023-08-14).

Mesen developer has not provided a way to report bug or to be contacted. I hope you can let them know this needs fix.

**Comment by oncemailtime** [comment]
https://github.com/SourMesen/Mesen2/commit/4b949021f5d15c884897d683815660558b3e4aca
